FROM node:20-alpine AS frontend-builder

WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ ./
RUN npm run build

FROM ghcr.io/opennmt/ctranslate2:4.7.1-ubuntu22.04-rocm7.2 AS runtime

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    AUDIO_DIR=/audios \
    OUTPUT_DIR=/output \
    WHISPER_DEVICE=rocm \
    ROCR_VISIBLE_DEVICES=0,1 \
    HSA_OVERRIDE_GFX_VERSION=9.0.6 \
    PYTHON_BIN=python3

WORKDIR /app

COPY backend/requirements.txt /app/backend/requirements.txt
RUN ${PYTHON_BIN} -m pip install --no-cache-dir -r /app/backend/requirements.txt

COPY backend /app/backend
COPY --from=frontend-builder /app/frontend/dist /app/frontend/dist
COPY docker-entrypoint.sh /app/docker-entrypoint.sh

RUN mkdir -p /audios /output
RUN chmod +x /app/docker-entrypoint.sh

RUN cd /tmp && curl -L https://raw.githubusercontent.com/sheldonrong/rocblas-radeon-vega/refs/heads/main/rocblas_72.tar.gz --output rocblas.tar.gz \
    && tar -xvf rocblas.tar.gz /opt/rocm-7.2.0/lib/rocblas/library/ && cp /tmp/rocblas/lib/rocblas/library/TensileLibrary_*_gfx906.* /opt/rocm-7.2.0/lib/rocblas/library/

WORKDIR /app/backend

EXPOSE 8000

ENTRYPOINT ["/app/docker-entrypoint.sh"]
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
