services:
  audio-transcript:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.rocm
    image: audio-transcript-rocm
    ports:
      - "8888:8000"
    environment:
      API_BASE_URL: http://192.168.0.117:8888
      WS_URL: ws://192.168.0.117:8888
      AUDIO_DIR: /audios
      OUTPUT_DIR: /output
      WHISPER_DEVICE: rocm
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    volumes:
      - /mnt/Storage/Storage/Pastebin:/audios
      - /mnt/Storage/Storage/AudioTranscription:/output
    restart: unless-stopped
